### ISSUE TITLE
Uninformative error message from ASimulatoR::simulate_alternative_splicing()

### ISSUE THREAD

**Issue by portomi** [biomedbigdata/ASimulatoR#2]
I was trying to figure out how simulate_alternative_splicing() works but simulate_alternative_splicing("/disk/work/shared/data/transcriptomes/gencode/gencode.v34", list("a3"=0.2, "a5"=0.2, "ir"=0.1, "es"=0.1, "ale"=0.1, "afe"=0.1, "mee"=0.1, "mes"=0.1), outdir = "./") resulted the following error message: 
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'i' in selecting a method for function '[': 'match' requires vector arguments

I could not resolve the error message on my own.

**Comment by quirinmanz** [comment]
Hi,
sorry for the problem you experienced. 
To be able to help I would need additional information:
1. What is the output of `simulate_alternative_splicing` until the error occurs?

2. How does your input directory (`/disk/work/shared/data/transcriptomes/gencode/gencode.v34`) look like?

Best,
Quirin

**Comment by portomi** [comment]
Hi,

Thank you for the prompt reaction.
This is the complete output. I copied here everithing as possibly the issue happens when the package is loaded:


>library("ASimulatoR")

Loading required package: data.table data.table
1.13.2 using 12 threads (see ?getDTthreads).  Latest news: r-datatable.com Loading required package: rtracklayer
Loading required package: GenomicRanges
Loading required package: stats4
Loading required package: BiocGenerics
Loading required package: parallel 
Attaching package: ‘BiocGenerics’ 
The following objects are masked from ‘package:parallel’:      clusterApply, clusterApplyLB, clusterCall, clusterEvalQ, clusterExport, clusterMap,     parApply, parCapply, parLapply, parLapplyLB, parRapply, parSapply, parSapplyLB 
The following objects are masked from ‘package:stats’:      IQR, mad, sd, var, xtabs 
The following objects are masked from ‘package:base’:      anyDuplicated, append, as.data.frame, basename, cbind, colnames, dirname, do.call,     duplicated, eval, evalq, Filter, Find, get, grep, grepl, intersect, is.unsorted,     lapply, Map, mapply, match, mget, order, paste, pmax, pmax.int, pmin, pmin.int,     Position, rank, rbind, Reduce, rownames, sapply, setdiff, sort, table, tapply,     union, unique, unsplit, which, which.max, which.min 
Loading required package: S4Vectors  Attaching package: ‘S4Vectors’ 
The following objects are masked from ‘package:data.table’:      first, second 
The following object is masked from ‘package:base’:      expand.grid 
Loading required package: IRanges  Attaching package: ‘IRanges’
The following object is masked from ‘package:data.table’:      shift
Loading required package: GenomeInfoDb Loading required package: polyester
Loading required package: pbmcapply 
> simulate_alternative_splicing("/disk/work/shared/data/transcriptomes/gencode/gencode.v34", list("a3"=0.2, "a5"=0.2, "ir"=0.1, "es"=0.1, "ale"=0.1, "afe"=0.1, "mee"=0.1, "mes"=0.1), outdir = "./")

found the following fasta files: gencode.v34_all_transcripts.fa, gencode.v34.transcripts.fa, gencode.v34.transcripts.pizzly.fa note that splice variants will only be constructed from chromosomes that have a corresponding fasta file  

importing gtf...
finished importing gtf 

Error in h(simpleError(msg, call)) :    error in evaluating the argument 'i' in selecting a method for function '[': 'match' requires vector arguments

 
**gencode.v34 includes the followings:**

gencode.v34.2wayconspseudos.gff3.gz
gencode.v34.2wayconspseudos.gtf.gz
gencode.v34.annotation.gff3.gz
gencode.v34.annotation.gtf
gencode.v34.annotation.gtf.gz
gencode.v34.basic.annotation.gff3.gz
gencode.v34.basic.annotation.gtf.gz
gencode.v34.chr_patch_hapl_scaff.annotation.gff3.gz
gencode.v34.chr_patch_hapl_scaff.annotation.gtf.gz
gencode.v34.chr_patch_hapl_scaff.basic.annotation.gff3.gz
gencode.v34.chr_patch_hapl_scaff.basic.annotation.gtf.gz
gencode.v34.lncRNA_transcripts.fa.gz
gencode.v34.long_noncoding_RNAs.gff3.gz
gencode.v34.long_noncoding_RNAs.gtf.gz
gencode.v34.metadata.Annotation_remark.gz
gencode.v34.metadata.EntrezGene.gz
gencode.v34.metadata.Exon_supporting_feature.gz
gencode.v34.metadata.Gene_source.gz
gencode.v34.metadata.HGNC.gz
gencode.v34.metadata.PDB.gz
gencode.v34.metadata.PolyA_feature.gz
gencode.v34.metadata.Pubmed_id.gz
gencode.v34.metadata.RefSeq.gz
gencode.v34.metadata.Selenocysteine.gz
gencode.v34.metadata.SwissProt.gz
gencode.v34.metadata.TrEMBL.gz
gencode.v34.metadata.Transcript_source.gz
gencode.v34.metadata.Transcript_supporting_feature.gz
gencode.v34.pc_transcripts.fa.gz
gencode.v34.pc_translations.fa.gz
gencode.v34.polyAs.gff3.gz
gencode.v34.polyAs.gtf.gz
gencode.v34.primary_assembly.annotation.gff3.gz
gencode.v34.primary_assembly.annotation.gtf.gz
gencode.v34.tRNAs.gff3.gz
gencode.v34.tRNAs.gtf.gz
gencode.v34.transcripts.fa
gencode.v34.transcripts.fa.gz
gencode.v34.transcripts.pizzly.fa
gencode.v34.transcripts.pizzly.fa.gz
gencode.v34_all_transcripts.fa


Cheers!
Tamas

**Comment by quirinmanz** [comment]
Hi Tamas,
thank you for the additional information. 

ASimulatoR requires genome fasta files with one file per chromosome i.e. <chr_name>.fa. 
I see that this may not be clear if you did not familiarize yourself with polyester, so I will add it to the documentation as well as a more informative error message and push the changes in a few minutes.

Could you tell me if that resolves your problem?

Best,
Quirin

**Comment by portomi** [comment]
Hi Quirin,

Thanks for the clarification; I missed this info.
Yes, issue resolved.

Best regards,
Tamas
