### ISSUE TITLE
fastq vs fasta

### ISSUE THREAD

**Issue by ls233** [biomedbigdata/ASimulatoR#6]
somehow for me, the tool produces output in the fasta format. Setting fastq = T in the parameter list for passing along to polyester doesn't  seem to have an effect. Any advice on this? Are you sure that your "simulate_alternative_splicing" function passes the "extras <- list(...)" further to polyester via "simulate_experiment"?

**Comment by quirinmanz** [comment]
Works for me, which version of polyester do you have installed?

**Comment by ls233** [comment]
> packageVersion("polyester")
[1] '1.32.0'

**Comment by quirinmanz** [comment]
How did you install polyester? It needs to be the custom polyester version. The corresponding repo is here: [https://github.com/biomedbigdata/polyester](https://github.com/biomedbigdata/polyester)
